# Generated by Django 3.2.7 on 2022-04-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20220404_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=2, upload_to='images'),
            preserve_default=False,
        ),
    ]
